#plugin 'cocoapods-user-defined-build-types'

#enable_user_defined_build_types!

#use_frameworks!

platform :ios, '9.0'

target 'Libffi_iOS_Example' do
  #pod 'Libffi_iOS_Framework', :path => '../'
  #pod 'Libffi_iOS_Library', :build_type => :dynamic_framework, :podspec => '../'

  target 'Libffi_iOS_Tests' do
    inherit! :search_paths

    
  end
end
